### ISSUE TITLE
Deploy script contains hardcoded role arn

### ISSUE THREAD

**Issue by trieloff** [jpb/ring-aws-lambda-adapter#4]
The example deploy script contains a hardcoded reference to `arn:aws:iam::002682819933:role/lambda_basic_execution`. This is leading to errors when deploying to a different account:

```
2016-03-18 12:51:01,041 INFO - Using API Gateway endpoint https://apigateway.us-east-1.amazonaws.com
2016-03-18 12:51:02,909 INFO - Attempting to create API from RAML definition. RAML file: resources/example.raml
2016-03-18 12:51:03,040 INFO - Creating API with name ring-aws-lambda-adapter-example
2016-03-18 12:51:03,325 INFO - Created API tkh9apuhyb
2016-03-18 12:51:03,625 INFO - Removing default model Empty
2016-03-18 12:51:03,772 INFO - Removing default model Error
2016-03-18 12:51:04,198 INFO - Creating method for api id tkh9apuhyb and resource id 9gkgtx5mcj with method GET
2016-03-18 12:51:04,458 INFO - Creating integration with type AWS
2016-03-18 12:51:04,708 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Lambda function ARN must be in same account (Service: null; Status Code: 400; Error Code: null; Request ID: b1471789-ecff-11e5-80db-076a5b55b0de)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1383)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
        at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
        at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
        at com.sun.proxy.$Proxy30.putIntegration(Unknown Source)
```

**Comment by russellwhitaker** [comment]
Specifically, here: https://github.com/jpb/ring-aws-lambda-adapter/blob/master/example/bin/deploy#L23
